### ISSUE TITLE
<!-- Google tag (gtag.js) --> <script async src="https://www.googletagmanager.com/gtag/js?id=AW-16759894456"> </script> <script>   window.dataLayer = window.dataLayer || [];   function gtag(){dataLayer.push(arguments);}   gtag('js', new Date());    gtag('config', 'AW-16759894456'); </script>

### ISSUE THREAD

**Issue by ilCatta-creator** [cattabiani/paradiseyoga_website#1]
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-16759894456">
</script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-16759894456');
</script>

**Comment by cattabiani** [comment]
added and commented in the code until we will find out if these lines are really useful or not
